name: build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install "poetry >=1.1.4, <2.0.0"
          poetry install
      - name: Linting
        run: |
          poetry run pre-commit run --all-files
          poetry run mypy xfuse tests scripts
          poetry run pylint xfuse tests scripts
      - name: Testing
        run: |
          poetry run pytest --cov=./xfuse --cov-report=xml
      - name: Upload coverage report
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          flags: unittests
          fail_ci_if_error: true
